import math

TIME_BETWEEN_SAMPLES = 300
SAMPLES_BETWEEN_DAYS = math.floor(24*60*60/TIME_BETWEEN_SAMPLES)
SAMPLES_BETWEEN_WEEKS = math.floor(SAMPLES_BETWEEN_DAYS*7)

Q = 12
TESTING_START_DAY = 28
TESTING_END_DAY = 29
